### ISSUE TITLE
train

### ISSUE THREAD

**Issue by xiao-ming-code** [majumderb/pabst#1]
Hello, could you please tell me the steps and commands of training and prediction

**Comment by majumderb** [comment]
Hi,

Our method doesn't require training a dialog model. You should use any transformer-based generative model as your dialog model. 

To train the dialog NLI classifier, see here: https://github.com/majumderb/pabst/blob/main/pabst/run_pplm_discrim_train.py
`--help` from the command line should give you all the arguments you can pass.

Once you have both the model (dialog model of your choice, and the dnli model), you can run inference using this code: https://github.com/majumderb/pabst/blob/main/pabst/run_pplm.py
Similarly, `--help` from the command line should give you all the arguments you can pass.
